export const countryData = [
  {
    country: "USA",
    currency: "USD",
    language: "English",
    avgTuitionUSD: 40000,
    avgLivingCostUSD: 15000,
    visaDifficulty: "Medium",
    workWhileStudying: "20 hrs/week",
    postStudyVisa: "OPT - 1 to 3 years",
    jobMarket: "Excellent",
    popularCities: ["New York", "San Francisco", "Boston", "Seattle"],
    popularFields: ["Computer Science", "Engineering", "Business", "Medicine"],
    pros: ["Top ranked universities", "Strong job market", "Diverse culture", "Research opportunities"],
    cons: ["High tuition fees", "Expensive healthcare", "Complex visa process"],
  },
  {
    country: "Canada",
    currency: "CAD",
    language: "English / French",
    avgTuitionUSD: 28000,
    avgLivingCostUSD: 12000,
    visaDifficulty: "Easy",
    workWhileStudying: "20 hrs/week",
    postStudyVisa: "PGWP - up to 3 years",
    jobMarket: "Very Good",
    popularCities: ["Toronto", "Vancouver", "Montreal", "Calgary"],
    popularFields: ["Computer Science", "Engineering", "Business", "Healthcare"],
    pros: ["PR pathway after studies", "Affordable tuition", "Safe country", "Multicultural"],
    cons: ["Harsh winters", "Competitive job market in some fields"],
  },
  {
    country: "UK",
    currency: "GBP",
    language: "English",
    avgTuitionUSD: 33000,
    avgLivingCostUSD: 14000,
    visaDifficulty: "Medium",
    workWhileStudying: "20 hrs/week",
    postStudyVisa: "Graduate Route - 2 years",
    jobMarket: "Good",
    popularCities: ["London", "Manchester", "Edinburgh", "Birmingham"],
    popularFields: ["Business", "Law", "Engineering", "Arts"],
    pros: ["1 year MS programs", "Rich history", "English speaking", "Strong alumni networks"],
    cons: ["Expensive living in London", "Post-Brexit work restrictions"],
  },
  {
    country: "Australia",
    currency: "AUD",
    language: "English",
    avgTuitionUSD: 31000,
    avgLivingCostUSD: 13000,
    visaDifficulty: "Easy",
    workWhileStudying: "48 hrs/fortnight",
    postStudyVisa: "485 Visa - 2 to 4 years",
    jobMarket: "Good",
    popularCities: ["Sydney", "Melbourne", "Brisbane", "Perth"],
    popularFields: ["Engineering", "Nursing", "Business", "IT"],
    pros: ["High quality of life", "PR pathway", "Safe environment", "Beautiful weather"],
    cons: ["Far from India", "Expensive cities", "Limited top ranked universities"],
  },
  {
    country: "Germany",
    currency: "EUR",
    language: "German / English",
    avgTuitionUSD: 1500,
    avgLivingCostUSD: 11000,
    visaDifficulty: "Medium",
    workWhileStudying: "120 full days/year",
    postStudyVisa: "18 months job seeker visa",
    jobMarket: "Very Good",
    popularCities: ["Munich", "Berlin", "Hamburg", "Frankfurt"],
    popularFields: ["Engineering", "Computer Science", "Automotive", "Science"],
    pros: ["Almost free tuition", "Strong engineering industry", "Central Europe location"],
    cons: ["Language barrier", "Blocked account required", "Competitive admissions"],
  },
  {
    country: "Singapore",
    currency: "SGD",
    language: "English",
    avgTuitionUSD: 25000,
    avgLivingCostUSD: 14000,
    visaDifficulty: "Easy",
    workWhileStudying: "16 hrs/week",
    postStudyVisa: "Employment Pass",
    jobMarket: "Excellent",
    popularCities: ["Singapore"],
    popularFields: ["Business", "Finance", "Computer Science", "Engineering"],
    pros: ["Gateway to Asia", "Top ranked universities", "Safe city", "English speaking"],
    cons: ["Small country", "Expensive living", "Limited universities"],
  },
];